# Copyright 2026 Super Serious Studios
#
# MIT License
#
#
#
# ── session.jl ───────────────────────────────────────────────────────────
# Phase 2a: Server-side session registry.
#
# Server-authoritative architecture: the App + widget tree live on the server.
# The client is a dumb cell renderer + keystroke pipe. Each attachment is
# tracked via a Session, keyed by an opaque SessionID.
#
# Sessions hold the App instance and the last Buffer sent to the client.
# That last_buffer is the diff base: when the server renders a new frame,
# diff_message (in protocol.jl) compares against it and ships only changed
# cells. If last_buffer is nothing, a full snapshot is sent instead.
#
# All registry mutations go through SESSIONS_LOCK (ReentrantLock). Never
# access SESSIONS directly — always use the public API below.
# ─────────────────────────────────────────────────────────────────────────

using Random: randstring

# ── SessionID ─────────────────────────────────────────────────────────────

"""
    SessionID

Opaque, 128-bit hex-encoded identifier for a client attachment session.
Generated by `new_session`; never constructed by hand in normal usage.
"""
struct SessionID
    id::String   # 32 hex characters — 128 bits of entropy
end

Base.:(==)(a::SessionID, b::SessionID) = a.id == b.id
Base.hash(s::SessionID, h::UInt) = hash(s.id, h)

# ── Session ───────────────────────────────────────────────────────────────

"""
    Session

Server-side per-client attachment state.

Fields:
- `id`              — opaque SessionID (matches the registry key)
- `app`             — server-side App instance (stays on server; never serialized)
- `last_buffer`     — last Buffer sent to this client; diff base for next frame
- `created_at`      — `time()` at creation
- `last_activity`   — `time()` updated on every input or snapshot/diff emission
"""
mutable struct Session
    id::SessionID
    app::Any                          # server-side App (stays on server)
    last_buffer::Union{Buffer, Nothing}  # diff base; nothing ⇒ force snapshot
    created_at::Float64
    last_activity::Float64
    injectors::Vector{Function}       # Phase 3: handlers called by inject_input
    geometry::Ref{Rect}              # current client terminal size (updated via WireResizeEvent)
end

# ── Registry ──────────────────────────────────────────────────────────────

const SESSIONS      = Dict{SessionID, Session}()
const SESSIONS_LOCK = ReentrantLock()

# ── Public API ────────────────────────────────────────────────────────────

"""
    new_session(app) → Session

Generate a fresh SessionID, wrap `app` in a Session, register it, and
return the Session. Thread-safe.
"""
function new_session(app)::Session
    id  = SessionID(randstring(['0':'9'; 'a':'f'], 32))
    now = time()
    s   = Session(id, app, nothing, now, now, Function[], Ref(Rect(1, 1, 80, 24)))
    lock(SESSIONS_LOCK) do
        SESSIONS[id] = s
    end
    frank_session_created(s)
    s
end

"""
    get_session(id::SessionID) → Union{Session, Nothing}

Look up a Session by ID. Returns `nothing` if the session does not exist.
Thread-safe.
"""
function get_session(id::SessionID)::Union{Session, Nothing}
    lock(SESSIONS_LOCK) do
        get(SESSIONS, id, nothing)
    end
end

"""
    close_session!(id::SessionID) → Bool

Remove the session from the registry. Returns `true` if the session existed
and was removed, `false` if it was not found. Thread-safe.
"""
function close_session!(id::SessionID)::Bool
    removed = lock(SESSIONS_LOCK) do
        haskey(SESSIONS, id) || return false
        delete!(SESSIONS, id)
        true
    end
    removed && frank_session_closed(id)
    removed
end

"""
    touch!(session::Session)

Update `last_activity` to `time()`. Call this on every input or frame
emission so idle-timeout logic has an accurate heartbeat. Thread-safe
for the field write (Float64 is atomic on LP64; lock not required, but
callers should hold SESSIONS_LOCK if they need a consistent snapshot).
"""
function touch!(session::Session)
    session.last_activity = time()
    nothing
end

"""
    list_sessions() → Vector{SessionID}

Return a snapshot of all currently registered session IDs. Thread-safe.
"""
function list_sessions()::Vector{SessionID}
    lock(SESSIONS_LOCK) do
        collect(keys(SESSIONS))
    end
end

"""
    register_input_handler!(session::Session, handler::Function)

Register an input handler for a session. Called when an authorised agent
injects input via `inject_input(subscription_id, event)`.

Multiple handlers may be registered; they are called in registration order.
Each handler receives the raw event object as its sole argument.
"""
function register_input_handler!(session::Session, handler::Function)
    push!(session.injectors, handler)
    return nothing
end
